/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
	preset: "ts-jest",
	testEnvironment: "jsdom",
	injectGlobals: true,
	moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
	transform: { "^.+\\.(ts|tsx)$": ["ts-jest", { tsconfig: { jsx: "react-jsx", module: "ESNext" } }] },
	testMatch: ["<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}", "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"],
	setupFilesAfterEnv: ["<rootDir>/src/setupTests.tsx"],
	moduleNameMapper: {
		"\\.(css|less|scss|sass)$": "identity-obj-proxy",
		"^vscrui$": "<rootDir>/src/__mocks__/vscrui.ts",
		"^@vscode/webview-ui-toolkit/react$": "<rootDir>/src/__mocks__/@vscode/webview-ui-toolkit/react.ts",
		"^@/(.*)$": "<rootDir>/src/$1",
		"^@roo/(.*)$": "<rootDir>/../src/shared/$1",
		"^@src/(.*)$": "<rootDir>/src/$1",
		"^src/i18n/setup$": "<rootDir>/src/__mocks__/i18n/setup.ts",
		"^\\.\\./setup$": "<rootDir>/src/__mocks__/i18n/setup.ts",
		"^\\./setup$": "<rootDir>/src/__mocks__/i18n/setup.ts",
		"^src/i18n/TranslationContext$": "<rootDir>/src/__mocks__/i18n/TranslationContext.tsx",
		"^\\.\\./TranslationContext$": "<rootDir>/src/__mocks__/i18n/TranslationContext.tsx",
		"^\\./TranslationContext$": "<rootDir>/src/__mocks__/i18n/TranslationContext.tsx",
		"^@src/utils/highlighter$": "<rootDir>/src/__mocks__/utils/highlighter.ts",
		"^shiki$": "<rootDir>/src/__mocks__/shiki.ts",
		"^react-markdown$": "<rootDir>/src/__mocks__/react-markdown.tsx",
	},
	reporters: [["jest-simple-dot-reporter", {}]],
	transformIgnorePatterns: [
		"/node_modules/(?!(shiki|rehype-highlight|react-remark|remark-gfm|mdast-util-gfm|mdast-util-gfm-table|mdast-util-gfm-strikethrough|mdast-util-gfm-task-list-item|mdast-util-gfm-autolink-literal|mdast-util-gfm-footnote|micromark-extension-gfm|micromark-extension-gfm-table|micromark-extension-gfm-strikethrough|micromark-extension-gfm-task-list-item|micromark-extension-gfm-autolink-literal|micromark-extension-gfm-footnote|unist-util-visit|unist-util-visit-parents|unist-util-find-after|unist-util-is|unist-util-stringify-position|vfile|vfile-message|unified|bail|is-plain-obj|trough|mdast-util-from-markdown|mdast-util-to-string|micromark|decode-named-character-reference|character-entities|markdown-table|zwitch|longest-streak|escape-string-regexp|hast-util-to-text|@vscode/webview-ui-toolkit|@microsoft/fast-react-wrapper|@microsoft/fast-element|@microsoft/fast-foundation|@microsoft/fast-web-utilities|exenv-es6|vscrui)/)",
	],
	roots: ["<rootDir>"],
	moduleDirectories: ["node_modules", "src"],
}
